#! /bin/sh

DIR=`dirname $0`
HOST=192.168.1.2

LIBPATH=/usr/local/lib #! /path/to/librcsc/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

IMAGE_OPTS="--hide-score-board --hide-player-number --hide-view-area --hide-pointto --hide-stamina --hide-team-grahip --hide-card --enlarge-mode --player-size 2 --ball-size 1.3 --geometry=280x167+1+1"

python $DIR/spectator/src/spectator_server.py &
sleep 3
$DIR/soccerwindow2-screenshot/bin/soccerwindow2-qt --host $HOST --connect --auto-reconnect-mode $IMAGE_OPTS $@ &
rcssmonitor --server-host $HOST  --connect --auto-reconnect-mode on 
