#! /bin/sh

DIR=`dirname $0`

LIBPATH= #! /path/to/librcsc/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

DEFAULT_OPTS="-c -d"
IMAGE_OPTS="--hide-score-board --hide-player-number --hide-view-area --hide-pointto --hide-stamina --hide-team-grahip --hide-card --enlarge-mode --player-size 2 --ball-size 1.3 --geometry=280x167+1+1"

$DIR/soccerwindow2-screenshot/bin/soccerwindow2-qt4 $DEFAULT_OPTS $IMAGE_OPTS $@ &
rcssmonitor -c &
python $DIR/spectator/src/spectator_server.py
